import { auth, currentUser } from "@clerk/nextjs/server";
import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";

const CreateProjectSchema = z.object({
  prompt: z
    .string()
    .min(1, "Prompt is required")
    .max(5000, "Prompt is too long"),
});

// API routes are dynamic by default, but explicit is good for clarity
// runtime = "nodejs" is required because:
// 1. We use Prisma (not supported in Edge runtime)
export const dynamic = "force-dynamic";
export const runtime = "nodejs";

export async function POST(req: Request) {
  try {
    const { userId } = await auth();
    const user = await currentUser();

    if (!userId || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    let body: unknown;
    try {
      body = await req.json();
    } catch {
      return NextResponse.json(
        { error: "Invalid JSON in request body" },
        { status: 400 },
      );
    }

    const validation = CreateProjectSchema.safeParse(body);

    if (!validation.success) {
      return NextResponse.json(
        {
          error: "Validation failed",
          details: validation.error.format(),
        },
        { status: 400 },
      );
    }

    const { prompt } = validation.data;

    // Upsert user to keep user data in sync
    await prisma.user.upsert({
      where: { clerkId: userId },
      update: {
        email: user.emailAddresses[0]?.emailAddress ?? "",
        firstName: user.firstName,
        lastName: user.lastName,
        imageUrl: user.imageUrl,
        updatedAt: new Date(),
      },
      create: {
        clerkId: userId,
        email: user.emailAddresses[0]?.emailAddress ?? "",
        firstName: user.firstName,
        lastName: user.lastName,
        imageUrl: user.imageUrl,
        updatedAt: new Date(),
      },
    });

    // Log deployment placeholder
    console.log(`[DEPLOY] Deploying app for prompt: ${prompt.trim()}`);

    // Create project - UUID is auto-generated by database via gen_random_uuid()
    const project = await prisma.project.create({
      data: {
        userId: userId,
        prompt: prompt.trim(),
        status: "DRAFT",
        updatedAt: new Date(),
      },
    });

    // Save the initial prompt as the first message in the chat
    await prisma.chatMessage.create({
      data: {
        projectId: project.id,
        role: "user",
        content: prompt.trim(),
      },
    });

    return NextResponse.json(project, { status: 201 });
  } catch (error) {
    console.error("[PROJECTS_POST]", error);

    // Don't expose internal error details in production
    return NextResponse.json(
      { error: "Failed to create project" },
      { status: 500 },
    );
  }
}
